import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';
import { logger } from '../services/logger';

/** Opens a GitOps PR carrying generated NetworkPolicies. Same GitHub-App
 *  bootstrap as gitops/rollbackService — keep the two in sync. */
export async function openNetpolPr(options: {
  repo: string; namespace: string; yaml: string;
}): Promise<{ prUrl: string }> {
  const match = options.repo.match(/github\.com\/([^/]+)\/([^/.]+)/);
  if (!match) throw new Error(`Invalid GitHub repository URL: ${options.repo}`);
  const owner = match[1];
  const repoName = match[2];

  const appOctokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: (process.env.GITHUB_APP_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
    },
  });
  const { data: installation } = await appOctokit.apps.getRepoInstallation({ owner, repo: repoName });
  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: (process.env.GITHUB_APP_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
      installationId: installation.id,
    },
  });

  const { data: repoInfo } = await octokit.repos.get({ owner, repo: repoName });
  const base = repoInfo.default_branch;
  const { data: baseRef } = await octokit.git.getRef({ owner, repo: repoName, ref: `heads/${base}` });

  const branch = `scorpion/netpol-${options.namespace}-${Date.now()}`;
  await octokit.git.createRef({
    owner, repo: repoName, ref: `refs/heads/${branch}`, sha: baseRef.object.sha,
  });

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo: repoName,
    path: `k8s/networkpolicies/${options.namespace}.yaml`,
    message: `feat(security): zero-trust NetworkPolicies for ${options.namespace}`,
    content: Buffer.from(options.yaml).toString('base64'),
    branch,
  });

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo: repoName,
    title: `feat(security): zero-trust NetworkPolicies for ${options.namespace}`,
    head: branch,
    base,
    body: 'Generated by Scorpion Operate phase: default-deny baseline plus declared service flows. Review the allowlist before merging.',
  });

  logger.info(`[NetPol] PR opened: ${pr.html_url}`);
  return { prUrl: pr.html_url };
}
