/**
 * Zero-trust NetworkPolicy generator: default-deny + DNS + explicit per-flow
 * allowances. Pure string output — delivery (download / GitOps PR) happens at
 * the route layer; Scorpion never applies these to a cluster.
 */

export interface ServiceFlow { from: string; to: string; port: number }
export interface NetPolInput { namespace: string; flows: ServiceFlow[] }

// DNS-1123 label — also blocks YAML metacharacters (:, #, *, !, newline) from
// reaching the hand-built documents (same injection class as Task 7 SAFE_PARAM).
const DNS_1123 = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/;
// Conservative k8s label-value whitelist for flow.from / flow.to.
const LABEL_VALUE = /^[A-Za-z0-9]([A-Za-z0-9_.-]{0,61}[A-Za-z0-9])?$/;

// Fail-secure: an invalid flow is skipped, not rendered — under default-deny
// its traffic simply stays denied instead of risking YAML corruption.
const isValidFlow = (flow: ServiceFlow): boolean =>
  LABEL_VALUE.test(flow.from) && LABEL_VALUE.test(flow.to);

const sanitize = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const doc = (lines: string[]): string => lines.join('\n');

function denyAll(namespace: string): string {
  return doc([
    'apiVersion: networking.k8s.io/v1',
    'kind: NetworkPolicy',
    'metadata:',
    '  name: default-deny-all',
    `  namespace: ${namespace}`,
    'spec:',
    '  podSelector: {}',
    '  policyTypes:',
    '    - Ingress',
    '    - Egress',
  ]);
}

function allowDns(namespace: string): string {
  return doc([
    'apiVersion: networking.k8s.io/v1',
    'kind: NetworkPolicy',
    'metadata:',
    '  name: allow-dns',
    `  namespace: ${namespace}`,
    'spec:',
    '  podSelector: {}',
    '  policyTypes:',
    '    - Egress',
    '  egress:',
    '    - to:',
    '        - namespaceSelector: {}',
    '          podSelector:',
    '            matchLabels:',
    '              k8s-app: kube-dns',
    '      ports:',
    '        - protocol: UDP',
    '          port: 53',
    '        - protocol: TCP',
    '          port: 53',
  ]);
}

function allowIngress(namespace: string, flow: ServiceFlow): string {
  return doc([
    'apiVersion: networking.k8s.io/v1',
    'kind: NetworkPolicy',
    'metadata:',
    `  name: allow-${sanitize(flow.from)}-to-${sanitize(flow.to)}-${flow.port}`,
    `  namespace: ${namespace}`,
    'spec:',
    '  podSelector:',
    '    matchLabels:',
    `      app: "${flow.to}"`,
    '  policyTypes:',
    '    - Ingress',
    '  ingress:',
    '    - from:',
    '        - podSelector:',
    '            matchLabels:',
    `              app: "${flow.from}"`,
    '      ports:',
    '        - protocol: TCP',
    `          port: ${flow.port}`,
  ]);
}

function allowEgress(namespace: string, flow: ServiceFlow): string {
  return doc([
    'apiVersion: networking.k8s.io/v1',
    'kind: NetworkPolicy',
    'metadata:',
    `  name: allow-egress-${sanitize(flow.from)}-to-${sanitize(flow.to)}-${flow.port}`,
    `  namespace: ${namespace}`,
    'spec:',
    '  podSelector:',
    '    matchLabels:',
    `      app: "${flow.from}"`,
    '  policyTypes:',
    '    - Egress',
    '  egress:',
    '    - to:',
    '        - podSelector:',
    '            matchLabels:',
    `              app: "${flow.to}"`,
    '      ports:',
    '        - protocol: TCP',
    `          port: ${flow.port}`,
  ]);
}

export function generateNetworkPolicies(input: NetPolInput): string {
  if (!DNS_1123.test(input.namespace)) {
    throw new Error('Invalid namespace: must be a DNS-1123 label');
  }
  const flows = input.flows.filter(isValidFlow);
  const docs = [
    denyAll(input.namespace),
    allowDns(input.namespace),
    ...flows.flatMap((f) => [allowIngress(input.namespace, f), allowEgress(input.namespace, f)]),
  ];
  return `# Generated by Scorpion — zero-trust baseline for namespace '${input.namespace}'\n`
    + docs.join('\n---\n') + '\n';
}
