import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';

export interface RollbackOptions {
  app: string;
  image: string;
  revision: string;
  repo: string;
  criticalCount: number;
}

export async function triggerRollback(options: RollbackOptions) {
  console.log(`[Rollback] Initiating rollback for ${options.app} due to ${options.criticalCount} critical CVEs`);
  
  // Extract owner and repo from URL
  const match = options.repo.match(/github\.com\/([^/]+)\/([^/.]+)/);
  if (!match) throw new Error(`Invalid GitHub repository URL: ${options.repo}`);
  
  const owner = match[1];
  const repoName = match[2];

  // 0. Get installation ID dynamically
  const appOctokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: (process.env.GITHUB_APP_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
    }
  });

  const { data: installation } = await appOctokit.apps.getRepoInstallation({ 
    owner, 
    repo: repoName 
  });

  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: (process.env.GITHUB_APP_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
      installationId: installation.id
    }
  });

  try {
    // 1. Get previous safe commit
    const commits = await octokit.repos.listCommits({ 
      owner, 
      repo: repoName, 
      per_page: 5 
    });
    
    // Find the previous commit (assuming the latest one is the current synced one)
    const currentSha = options.revision;
    const currentIndex = commits.data.findIndex(c => c.sha === currentSha);
    const safeCommit = currentIndex >= 0 && currentIndex < commits.data.length - 1 
      ? commits.data[currentIndex + 1] 
      : commits.data[1]; // Fallback to second latest if current not found

    // 2. Open rollback PR
    const branch = `scorpion/rollback-${options.app}-${Date.now()}`;
    
    // Get main branch SHA for base
    const mainRef = await octokit.git.getRef({ owner, repo: repoName, ref: `heads/main` });
    
    // Create new branch from safe commit
    await octokit.git.createRef({
      owner, 
      repo: repoName,
      ref: `refs/heads/${branch}`,
      sha: safeCommit.sha
    });

    const pr = await octokit.pulls.create({
      owner, 
      repo: repoName,
      title: `[SCORPION] Rollback ${options.app} — ${options.criticalCount} critical CVEs in deployed image`,
      body: `## Security Rollback\n\nSCORPION detected **${options.criticalCount} critical CVEs** in image \`${options.image}\` deployed to \`${options.app}\`.\n\nThis PR reverts deployment configuration to commit \`${safeCommit.sha.slice(0, 7)}\` (${safeCommit.commit.message}).\n\n### Findings Summary\n- **App**: ${options.app}\n- **Vulnerable Image**: \`${options.image}\`\n- **Critical Vulnerabilities**: ${options.criticalCount}\n\n> Auto-generated by SCORPION GitOps Security Gate`,
      head: branch,
      base: 'main'
    });

    console.log(`[Rollback] Created PR #${pr.data.number}: ${pr.data.html_url}`);
    return pr.data;
  } catch (error: any) {
    console.error(`[Rollback] Failed to trigger rollback for ${options.app}:`, error);
    throw error;
  }
}
