import { Octokit } from '@octokit/rest';
import axios from 'axios';
import { databases, COLLECTIONS, DB_ID } from '../lib/appwrite';

export interface PRResult {
    url: string;
    branch_name: string;
    status: 'opened' | 'failed';
}

/**
 * Orchestrates the PR creation workflow for a vulnerability fix.
 */
export const createPullRequest = async (fixId: string): Promise<PRResult> => {
    try {
        // 1. Fetch fix, vulnerability and repository details sequentially (No joins in Appwrite)
        const fix = await databases.getDocument(DB_ID, 'vulnerability_fixes', fixId);
        const vulnerability = await databases.getDocument(DB_ID, COLLECTIONS.VULNERABILITIES, fix.vulnerability_id);
        const repository = await databases.getDocument(DB_ID, COLLECTIONS.REPOSITORIES, vulnerability.repo_id);

        // 2. Safety Check: Ensure the code_diff isn't suspiciously short or empty
        if (!fix.code_diff || fix.code_diff.trim().length < 20) {
            throw new Error('Proposed security fix appears incomplete or empty. Aborting PR creation to prevent data loss.');
        }

        const provider = repository.url.includes('github.com') ? 'github' : 'gitlab';

        // 2. Prepare PR details
        const branchName = `stackpilot/fix-${fixId.substring(0, 8)}`;
        const prTitle = `[StackPilot] Fix: ${vulnerability.message.substring(0, 50)}...`;
        const prBody = `
## 🛡️ StackPilot Automated Security Fix

**Vulnerability:** ${vulnerability.message}
**Severity:** ${vulnerability.severity}
**File:** \`${vulnerability.file_path}\`

### 🧠 AI Explanation:
${fix.explanation}

### ⚠️ Risk Mitigation:
This fix was automatically generated by StackPilot to address a detected security finding. Please review the diff carefully before merging.

---
*Generated by [StackPilot](https://stackpilot.io)*
        `.trim();

        if (provider === 'github') {
            return await createGitHubPR(repository, branchName, vulnerability.file_path, fix.code_diff, prTitle, prBody);
        } else {
            return await createGitLabPR(repository, branchName, vulnerability.file_path, fix.code_diff, prTitle, prBody);
        }
    } catch (err: any) {
        console.error(`[GitProviderService] Failed to create PR: ${err.message}`);
        try {
            await databases.updateDocument(DB_ID, 'vulnerability_fixes', fixId, {
                pr_status: 'failed'
            });
        } catch (updateErr) {
            console.error('[GitProviderService] Error updating PR status:', updateErr);
        }
        throw err;
    }
};

/**
 * GitHub implementation using Octokit
 */
async function createGitHubPR(repo: any, branchName: string, filePath: string, newContent: string, title: string, body: string): Promise<PRResult> {
    const token = process.env.GITHUB_TOKEN;
    if (!token) throw new Error('GITHUB_TOKEN not configured');

    const octokit = new Octokit({ auth: token });
    const repoMatch = repo.url.match(/github\.com\/([^/]+)\/([^/.]+)/);
    if (!repoMatch) throw new Error('Invalid GitHub URL');

    const [_, owner, repoName] = repoMatch;

    // 1. Get default branch SHA
    const { data: repoInfo } = await octokit.repos.get({ owner, repo: repoName });
    const defaultBranch = repoInfo.default_branch;
    const { data: ref } = await octokit.git.getRef({ owner, repo: repoName, ref: `heads/${defaultBranch}` });
    const baseSha = ref.object.sha;

    // 2. Create new branch
    await octokit.git.createRef({
        owner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: baseSha
    });

    // 3. Create commit with fixed content
    // Note: This is a simplified commit. For large projects, we'd use Trees/Blobs APIs.
    await octokit.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: filePath,
        message: 'Applying StackPilot security fix',
        content: Buffer.from(newContent).toString('base64'),
        branch: branchName,
        // We get the current file SHA to ensure we're updating correctly
        sha: (await octokit.repos.getContent({ owner, repo: repoName, path: filePath, ref: branchName }) as any).data.sha
    });

    // 4. Create Pull Request
    const { data: pr } = await octokit.pulls.create({
        owner,
        repo: repoName,
        title,
        body,
        head: branchName,
        base: defaultBranch
    });

    return {
        url: pr.html_url,
        branch_name: branchName,
        status: 'opened'
    };
}

/**
 * GitLab implementation using REST API
 */
async function createGitLabPR(repo: any, branchName: string, filePath: string, newContent: string, title: string, body: string): Promise<PRResult> {
    const token = process.env.GITLAB_TOKEN;
    if (!token) throw new Error('GITLAB_TOKEN not configured');

    const projectId = encodeURIComponent(repo.url.replace(/.*gitlab\.com\//, '').replace(/\.git$/, ''));
    const apiBase = 'https://gitlab.com/api/v4';

    // 1. Create branch
    await axios.post(`${apiBase}/projects/${projectId}/repository/branches`, {
        branch: branchName,
        ref: 'main' // Assuming main as default, should ideally fetch default branch
    }, { headers: { 'PRIVATE-TOKEN': token } });

    // 2. Commit fix
    await axios.post(`${apiBase}/projects/${projectId}/repository/commits`, {
        branch: branchName,
        commit_message: 'Applying StackPilot security fix',
        actions: [{
            action: 'update',
            file_path: filePath,
            content: newContent
        }]
    }, { headers: { 'PRIVATE-TOKEN': token } });

    // 3. Create Merge Request
    const { data: mr } = await axios.post(`${apiBase}/projects/${projectId}/merge_requests`, {
        source_branch: branchName,
        target_branch: 'main',
        title,
        description: body
    }, { headers: { 'PRIVATE-TOKEN': token } });

    return {
        url: mr.web_url,
        branch_name: branchName,
        status: 'opened'
    };
}
