import { Request, Response } from 'express';
import { deduplicateFindings } from '../deduplication';
// @ts-nocheck

/**
 * GET /api/dashboard/metrics
 * Returns governance metrics for the SCORPION dashboard.
 */
export const getMetrics = async (req: Request, res: Response) => {
  try {
    // 1. Fetch raw findings (pre‑deduplication). This function should return an array of findings
    //    as stored in the DB or generated by the latest scan.
    const rawFindings = await getRawFindings(); // each item follows the original Finding DTO

    // 2. Run deduplication on the raw data to obtain unique findings.
    const dedupedFindings = deduplicateFindings(rawFindings);

    // 3. Compute basic metrics.
    const totalRawFindings = rawFindings.length;
    const totalUniqueFindings = dedupedFindings.length;
    const noiseReductionPercentage = totalRawFindings
      ? ((totalRawFindings - totalUniqueFindings) / totalRawFindings) * 100
      : 0;

    // 4. Compliance mapping – simple hard‑coded example. Extend as needed.
    const complianceMapping: Record<string, number> = {
      // scanner type → count of findings mapped to a compliance control
      sast: dedupedFindings.filter((f) => f.scannerSource?.includes('semgrep')).length,
      secret: dedupedFindings.filter((f) => f.scannerSource?.includes('gitleaks')).length,
      sca: dedupedFindings.filter((f) => f.scannerSource?.includes('trivy')).length,
      iac: 0, // placeholder – populate when IaC scanners are added
    };

    // 5. MTTR – for demo purposes we return a static value. Replace with real audit‑log calculation.
    const averageMTTRMinutes = 5; // placeholder value

    const payload = {
      totalRawFindings,
      totalUniqueFindings,
      noiseReductionPercentage: Number(noiseReductionPercentage.toFixed(2)),
      complianceMapping,
      averageMTTRMinutes,
    };

    res.json(payload);
  } catch (err) {
    console.error('Failed to compute dashboard metrics', err);
    res.status(500).json({ error: 'Unable to compute metrics' });
  }
};
