import express, { Request } from 'express';
import { startBuild } from '../build/buildService';
import { auditLog } from '../services/auditService';
import { databases, COLLECTIONS, DB_ID, Query } from '../lib/appwrite';
import { assertRepoAccess, resolveOwnershipScope, TenantAccessError } from '../services/tenancyService';

interface AuthenticatedRequest extends Request {
  user?: { $id: string; email?: string };
}

const router = express.Router();

/**
 * POST /api/builds/trigger
 * Triggers a new build pipeline
 */
router.post('/trigger', async (req: AuthenticatedRequest, res) => {
  try {
    const { repoId, branch } = req.body;
    const userId = req.user?.$id;
    const triggeredBy = req.user?.email || 'unknown';

    if (!repoId || !branch) {
      return res.status(400).json({ error: 'repoId and branch are required' });
    }

    await assertRepoAccess(repoId, userId || '');

    const pipelineId = await startBuild(repoId, branch, triggeredBy);

    // Audit log
    await auditLog({
      action: 'build.triggered',
      actor: triggeredBy,
      actorEmail: triggeredBy,
      resource: 'build_pipelines',
      resourceId: pipelineId,
      details: { repoId, branch }
    });

    res.status(202).json({
      message: 'Build triggered successfully',
      pipelineId
    });
  } catch (err) {
    if (err instanceof TenantAccessError) return res.status(403).json({ error: err.message });
    res.status(500).json({ error: 'Failed to trigger build', details: err instanceof Error ? err.message : 'unknown error' });
  }
});

/**
 * GET /api/builds
 * List all builds with optional filters
 */
router.get('/', async (req: AuthenticatedRequest, res) => {
  try {
    const { repoId, status, limit = 50 } = req.query;
    const userId = req.user?.$id;

    if (repoId) {
      await assertRepoAccess(String(repoId), userId || '');
    }

    const queries: string[] = [
      Query.orderDesc('$createdAt'),
      Query.limit(Number(limit))
    ];

    if (repoId) {
      queries.push(Query.equal('repoId', String(repoId)));
    } else {
      const scope = await resolveOwnershipScope(req, userId || '');
      const ownedRepos = await databases.listDocuments(DB_ID, COLLECTIONS.REPOSITORIES, [Query.equal(scope.field, scope.value)]);
      const repoIds = ownedRepos.documents.map(r => r.$id);
      queries.push(Query.equal('repoId', repoIds.length > 0 ? repoIds : ['__none__']));
    }
    if (status) queries.push(Query.equal('status', String(status)));

    const results = await databases.listDocuments(DB_ID, COLLECTIONS.BUILD_PIPELINES, queries);
    res.json(results);
  } catch (err) {
    if (err instanceof TenantAccessError) return res.status(403).json({ error: err.message });
    res.status(500).json({ error: 'Failed to fetch builds', details: err instanceof Error ? err.message : 'unknown error' });
  }
});

/**
 * GET /api/builds/:id
 * Get a single build with logs
 */
router.get('/:id', async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user?.$id;
    const doc = await databases.getDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, req.params.id);
    await assertRepoAccess(doc.repoId, userId || '');
    res.json(doc);
  } catch (err) {
    if (err instanceof TenantAccessError) return res.status(403).json({ error: err.message });
    res.status(404).json({ error: 'Build not found', details: err instanceof Error ? err.message : 'unknown error' });
  }
});

/**
 * POST /api/builds/:id/cancel
 * Cancel a running build
 */
router.post('/:id/cancel', async (req: AuthenticatedRequest, res) => {
  try {
    const buildId = req.params.id;
    const userId = req.user?.$id;
    const userEmail = req.user?.email || 'unknown';

    const doc = await databases.getDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, buildId);
    await assertRepoAccess(doc.repoId, userId || '');
    if (doc.status !== 'running') {
      return res.status(400).json({ error: `Cannot cancel a build in status: ${doc.status}` });
    }

    // Update status in Appwrite
    const updated = await databases.updateDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, buildId, {
      status: 'cancelled',
      finishedAt: new Date().toISOString(),
      logs: doc.logs + '\n[SYSTEM]: Build cancelled by user.\n'
    });

    // Audit log
    await auditLog({
      action: 'build.cancelled',
      actor: userEmail,
      actorEmail: userEmail,
      resource: 'build_pipelines',
      resourceId: buildId
    });

    res.json({ message: 'Build cancelled', build: updated });
  } catch (err) {
    if (err instanceof TenantAccessError) return res.status(403).json({ error: err.message });
    res.status(500).json({ error: 'Failed to cancel build', details: err instanceof Error ? err.message : 'unknown error' });
  }
});

/**
 * GET /api/builds/:id/artifacts
 * Get artifacts generated by the build
 */
router.get('/:id/artifacts', async (req: AuthenticatedRequest, res) => {
  try {
    const buildId = req.params.id;
    const userId = req.user?.$id;

    const build = await databases.getDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, buildId);
    await assertRepoAccess(build.repoId, userId || '');

    const queries = [
      Query.equal('buildId', buildId),
      Query.limit(100)
    ];

    const results = await databases.listDocuments(DB_ID, COLLECTIONS.BUILD_ARTIFACTS, queries);
    res.json(results);
  } catch (err) {
    if (err instanceof TenantAccessError) return res.status(403).json({ error: err.message });
    res.status(500).json({ error: 'Failed to fetch artifacts', details: err instanceof Error ? err.message : 'unknown error' });
  }
});

export default router;
