import express from 'express';
import { startBuild } from '../build/buildService';
import { auditLog } from '../services/auditService';
import { databases, COLLECTIONS, DB_ID, Query } from '../lib/appwrite';

const router = express.Router();

/**
 * POST /api/builds/trigger
 * Triggers a new build pipeline
 */
router.post('/trigger', async (req, res) => {
  try {
    const { repoId, branch } = req.body;
    const triggeredBy = (req as any).user?.email || 'unknown';

    if (!repoId || !branch) {
      return res.status(400).json({ error: 'repoId and branch are required' });
    }

    const pipelineId = await startBuild(repoId, branch, triggeredBy);

    // Audit log
    await auditLog({
      action: 'build.triggered',
      actor: triggeredBy,
      actorEmail: triggeredBy,
      resource: 'build_pipelines',
      resourceId: pipelineId,
      details: { repoId, branch }
    });

    res.status(202).json({ 
      message: 'Build triggered successfully', 
      pipelineId 
    });
  } catch (err: any) {
    res.status(500).json({ error: 'Failed to trigger build', details: err.message });
  }
});

/**
 * GET /api/builds
 * List all builds with optional filters
 */
router.get('/', async (req, res) => {
  try {
    const { repoId, status, limit = 50 } = req.query;
    
    const queries: string[] = [
      Query.orderDesc('$createdAt'),
      Query.limit(Number(limit))
    ];

    if (repoId) queries.push(Query.equal('repoId', String(repoId)));
    if (status) queries.push(Query.equal('status', String(status)));

    const results = await databases.listDocuments(DB_ID, COLLECTIONS.BUILD_PIPELINES, queries);
    res.json(results);
  } catch (err: any) {
    res.status(500).json({ error: 'Failed to fetch builds', details: err.message });
  }
});

/**
 * GET /api/builds/:id
 * Get a single build with logs
 */
router.get('/:id', async (req, res) => {
  try {
    const doc = await databases.getDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, req.params.id);
    res.json(doc);
  } catch (err: any) {
    res.status(404).json({ error: 'Build not found', details: err.message });
  }
});

/**
 * POST /api/builds/:id/cancel
 * Cancel a running build
 */
router.post('/:id/cancel', async (req, res) => {
  try {
    const buildId = req.params.id;
    const userEmail = (req as any).user?.email || 'unknown';

    const doc = await databases.getDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, buildId);
    if (doc.status !== 'running') {
      return res.status(400).json({ error: `Cannot cancel a build in status: ${doc.status}` });
    }

    // Update status in Appwrite
    const updated = await databases.updateDocument(DB_ID, COLLECTIONS.BUILD_PIPELINES, buildId, {
      status: 'cancelled',
      finishedAt: new Date().toISOString(),
      logs: doc.logs + '\n[SYSTEM]: Build cancelled by user.\n'
    });

    // Audit log
    await auditLog({
      action: 'build.cancelled',
      actor: userEmail,
      actorEmail: userEmail,
      resource: 'build_pipelines',
      resourceId: buildId
    });

    res.json({ message: 'Build cancelled', build: updated });
  } catch (err: any) {
    res.status(500).json({ error: 'Failed to cancel build', details: err.message });
  }
});

/**
 * GET /api/builds/:id/artifacts
 * Get artifacts generated by the build
 */
router.get('/:id/artifacts', async (req, res) => {
  try {
    const buildId = req.params.id;
    const queries = [
      Query.equal('buildId', buildId),
      Query.limit(100)
    ];

    const results = await databases.listDocuments(DB_ID, COLLECTIONS.BUILD_ARTIFACTS, queries);
    res.json(results);
  } catch (err: any) {
    res.status(500).json({ error: 'Failed to fetch artifacts', details: err.message });
  }
});

export default router;
