import { Router, Request, Response } from 'express';
import { Octokit } from '@octokit/rest';
import simpleGit from 'simple-git';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';

const router = Router();

interface CreatePRBody {
  findingId: string;
  repoUrl: string;        // e.g. "https://github.com/owner/repo"
  filePath: string;       // relative path inside repo, e.g. "src/auth/login.ts"
  fixedContent: string;   // the full fixed file content from Gemini
  branchName?: string;
  prTitle?: string;
  prBody?: string;
  vulnerabilityTitle: string;
  severity: string;
}

router.post('/create-pr', async (req: Request, res: Response) => {
  const {
    findingId,
    repoUrl,
    filePath,
    fixedContent,
    vulnerabilityTitle,
    severity,
    branchName = `scorpion/fix-${findingId.slice(0, 8)}`,
    prTitle = `fix(security): ${vulnerabilityTitle}`,
    prBody,
  }: CreatePRBody = req.body;

  // Validate required fields
  if (!repoUrl || !filePath || !fixedContent || !findingId) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  // Parse owner/repo from URL
  const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?$/);
  if (!match) {
    return res.status(400).json({ error: 'Invalid GitHub repo URL' });
  }
  const [, owner, repo] = match;

  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'scorpion-'));

  try {
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const baseBranch = repoData.default_branch;

    // 1. Clone the repo into a temp directory
    const git = simpleGit();
    const cloneUrl = `https://${process.env.GITHUB_TOKEN}@github.com/${owner}/${repo}.git`;
    await git.clone(cloneUrl, tmpDir, ['--depth', '1']);

    const repoGit = simpleGit(tmpDir);

    // 2. Create and switch to the fix branch
    await repoGit.checkoutLocalBranch(branchName);

    // 3. Write the fixed file content
    const targetFile = path.join(tmpDir, filePath);
    await fs.mkdir(path.dirname(targetFile), { recursive: true });
    await fs.writeFile(targetFile, fixedContent, 'utf-8');

    // 4. Commit and push
    await repoGit.add(filePath);
    await repoGit.commit(`fix(security): auto-remediate ${vulnerabilityTitle} [SCORPION]`);
    await repoGit.push('origin', branchName);

    // 5. Open the Pull Request via GitHub API
    const defaultPrBody = prBody ?? buildPRBody(vulnerabilityTitle, severity, findingId);

    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: defaultPrBody,
      head: branchName,
      base: baseBranch,
    });

    return res.json({
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: branchName,
    });

  } catch (err: any) {
    console.error('[SCORPION] PR creation failed:', err.message);
    return res.status(500).json({ error: err.message });
  } finally {
    // Always clean up the temp clone
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
});

function buildPRBody(title: string, severity: string, findingId: string): string {
  return `## SCORPION Auto-Remediation

**Vulnerability:** ${title}  
**Severity:** ${severity}  
**Finding ID:** \`${findingId}\`

### What changed
This PR was automatically generated by [SCORPION](https://github.com/your-org/scorpion) using Gemini 1.5 Flash to produce a targeted fix for the above vulnerability.

### Review checklist
- [ ] Diff looks correct and doesn't break existing logic
- [ ] Tests pass in CI
- [ ] No unintended side effects

> Auto-generated by SCORPION · Do not merge without review
`;
}

export default router;
