import { Router, Response, Request } from 'express';
import { databases, DB_ID, Query } from '../lib/appwrite';
import { verifyUser } from '../middleware/auth';
import { logAuditEvent } from '../utils/auditLogger';
import PDFDocument from 'pdfkit';
import { Parser } from 'json2csv';

const router = Router();

router.post('/export', verifyUser, async (req: Request, res: Response) => {
    const { repo_id, format, from, to } = req.body;
    if (!repo_id) return res.status(400).json({ error: 'repo_id is required' });

    try {
        // 1. Fetch Repository Details
        const repo = await databases.getDocument(DB_ID, 'repositories', repo_id);

        // 2. Fetch Findings
        const queries = [Query.equal('repo_id', repo_id)];
        if (from) queries.push(Query.greaterThanEqual('$createdAt', from));
        if (to) queries.push(Query.lessThanEqual('$createdAt', to));
        queries.push(Query.limit(5000));

        const findingsResponse = await databases.listDocuments(DB_ID, 'findings', queries);
        const findings = findingsResponse.documents;

        const userId = (req as any).user?.$id;
        await logAuditEvent('REPORT_EXPORTED', `Security report generated as ${format.toUpperCase()} for ${repo.name}`, userId, repo_id);

        if (format === 'csv') {
            const fields = ['title', 'severity', 'type', 'file_path', 'cve_id', 'status', '$createdAt'];
            const opts = { fields };
            const parser = new Parser(opts);
            const csv = parser.parse(findings);

            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename="scorpion-report.csv"');
            return res.status(200).send(csv);
        }

        if (format === 'pdf') {
            const doc = new PDFDocument({ margin: 50 });
            const filename = `scorpion-report-${repo.name}-${Date.now()}.pdf`;

            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

            doc.pipe(res);

            // Header
            doc.fontSize(25).text('SCORPION SECURITY REPORT', { align: 'center' });
            doc.moveDown();
            doc.fontSize(16).text(`Repository: ${repo.name}`, { align: 'left' });
            doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: 'left' });
            doc.moveDown();

            // Summary
            const summary = {
                critical: findings.filter(f => f.severity.toLowerCase() === 'critical').length,
                high: findings.filter(f => f.severity.toLowerCase() === 'high').length,
                medium: findings.filter(f => f.severity.toLowerCase() === 'medium').length,
                low: findings.filter(f => f.severity.toLowerCase() === 'low').length
            };

            doc.fontSize(14).text('Executive Summary', { underline: true });
            doc.fontSize(12).text(`Total Findings: ${findings.length}`);
            doc.fillColor('red').text(`Critical: ${summary.critical}`);
            doc.fillColor('orange').text(`High: ${summary.high}`);
            doc.fillColor('yellow').text(`Medium: ${summary.medium}`);
            doc.fillColor('green').text(`Low: ${summary.low}`);
            doc.fillColor('black');
            doc.moveDown();

            // Findings Table
            doc.fontSize(14).text('Findings Detail', { underline: true });
            doc.moveDown();

            findings.forEach((f, i) => {
                if (doc.y > 700) doc.addPage();
                doc.fontSize(10).font('Helvetica-Bold').text(`${i + 1}. ${f.title}`);
                doc.font('Helvetica').fontSize(8)
                    .text(`Severity: ${f.severity.toUpperCase()} | Type: ${f.type.toUpperCase()}`)
                    .text(`Path: ${f.file_path}`)
                    .text(`Detected: ${new Date(f.$createdAt).toLocaleString()}`);
                doc.moveDown(0.5);
            });

            // Footer
            const range = doc.bufferedPageRange();
            for (let i = range.start; i < range.start + range.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(8).text(
                    `Generated by Scorpion at ${new Date().toISOString()}`,
                    50,
                    doc.page.height - 50,
                    { align: 'center' }
                );
            }

            doc.end();
            return;
        }

        res.status(400).json({ error: 'Invalid format. Use pdf or csv.' });
    } catch (err: any) {
        console.error('[Report API Error]', err.message);
        res.status(500).json({ error: 'Internal server error' });
    }
});

export default router;
